export type Sentiment = 'positive' | 'neutral' | 'negative' | 'unknown';
export interface SentimentResult { sentiment: Sentiment; score: number; confidence: number; provider: string; model: string; }
export interface SentimentProvider { analyzeSentiment(text: string): Promise<SentimentResult>; }
const positive=['avanço','crescimento','melhora','aprovação','vitória','positivo','sucesso','investimento','recorde','lucro','alta','expansão','acordo','inovação','emprego','recuperação','benefício','premiação','conquista'];
const negative=['crise','queda','denúncia','denuncia','investigação','investigacao','fraude','morte','risco','negativo','problema','prejuízo','prejuizo','corrupção','corrupcao','corrupto','corrupta','demissão','demissao','violência','violencia','acidente','rejeição','rejeicao','condenação','condenacao','escândalo','escandalo','escândalos','escandalos','falha','ameaça','ameaca','inflação','inflacao','ladrão','ladrao','ladra','ladrões','ladroes','bandido','bandida','bandidos','bandidas','criminoso','criminosa','criminosos','criminosas','quadrilha','roubo','roubando','roubou','rouba','roubar','crime','crimes','golpe','golpista','golpistas','canalha','canalhas','vagabundo','vagabunda','burro','burra','mentiroso','mentirosa','mentira','culpado','culpada','mensalão','mensalao','petrolão','petrolao','exorbitante','exorbitantes','falta','insegurança','inseguranca','atrasado','atrasada','atrasados','atrasadas','desemprego','fome','abandono','descaso','desvio','desvios','superfaturamento'];
const strongNegative=new Set(['ladrão','ladrao','ladra','ladrões','ladroes','bandido','bandida','bandidos','bandidas','criminoso','criminosa','criminosos','criminosas','quadrilha','roubo','roubando','roubou','rouba','roubar','corrupção','corrupcao','corrupto','corrupta','fraude','golpe','golpista','golpistas','mensalão','mensalao','petrolão','petrolao','escândalo','escandalo','escândalos','escandalos','exorbitante','exorbitantes','fome','desvio','desvios','superfaturamento']);
const negations=new Set(['não','nao','nunca','jamais','sem','nem']);const intensifiers=new Set(['muito','forte','grande','grave','recorde','extremamente','significativo','significativa']);
const normalize=(value:string)=>value.toLocaleLowerCase('pt-BR').replace(/[^\p{L}\p{N}\s-]/gu,' ').replace(/\s+/g,' ').trim();
class ContextualHeuristicProvider implements SentimentProvider{async analyzeSentiment(text:string){const tokens=normalize(text).split(' ').filter(Boolean);let raw=0,hits=0,strongHits=0;tokens.forEach((token,index)=>{const polarity=positive.includes(token)?1:negative.includes(token)?-1:0;if(!polarity)return;const window=tokens.slice(Math.max(0,index-3),index),negated=window.some(word=>negations.has(word));const weight=strongNegative.has(token)?2:1;raw+=(negated?-polarity:polarity)*weight*(window.some(word=>intensifiers.has(word))?1.4:1);hits++;if(strongNegative.has(token)&&!negated)strongHits++});let score=Math.max(-1,Math.min(1,raw/Math.max(3,hits)));if(strongHits&&score>-.45)score=-.45;const confidence=Math.min(.94,.5+Math.abs(score)*.3+Math.min(hits,5)*.025+Math.min(strongHits,2)*.04);return{sentiment:(score>.08?'positive':score<-.08?'negative':'neutral') as Sentiment,score,confidence,provider:'internal',model:'contextual-pt-v3'}}}
let contextualCalls=0;
class HybridSentimentProvider implements SentimentProvider{private fallback=new ContextualHeuristicProvider();async analyzeSentiment(text:string):Promise<SentimentResult>{const local=await this.fallback.analyzeSentiment(text),token=process.env.HF_TOKEN,limit=Math.max(0,Number(process.env.HF_SENTIMENT_MAX_CALLS??8));if(local.sentiment==='negative'&&local.score<=-.45)return local;if(!token||contextualCalls>=limit||text.trim().length<35)return local;contextualCalls++;try{const model=process.env.HF_SENTIMENT_MODEL?.trim()||process.env.HF_MODEL?.trim()||'Qwen/Qwen2.5-7B-Instruct';const response=await fetch('https://router.huggingface.co/v1/chat/completions',{method:'POST',headers:{authorization:`Bearer ${token}`,'content-type':'application/json'},body:JSON.stringify({model,messages:[{role:'system',content:'Classifique o sentimento em relação ao assunto principal, considerando negação e contexto. Responda somente JSON: {"sentiment":"positive|neutral|negative","score":numero de -1 a 1,"confidence":numero de 0 a 1}.'},{role:'user',content:text.slice(0,1800)}],temperature:0,max_tokens:80}),signal:AbortSignal.timeout(8000)});const payload=await response.json() as {choices?:Array<{message?:{content?:string}}>};if(!response.ok)throw new Error(`HTTP ${response.status}`);const content=payload.choices?.[0]?.message?.content??'',start=content.indexOf('{'),end=content.lastIndexOf('}');if(start<0||end<=start)throw new Error('JSON inválido');const parsed=JSON.parse(content.slice(start,end+1)) as {sentiment?:string;score?:number;confidence?:number};if(!['positive','neutral','negative'].includes(parsed.sentiment??''))throw new Error('Classe inválida');return{sentiment:parsed.sentiment as Sentiment,score:Math.max(-1,Math.min(1,Number(parsed.score??0))),confidence:Math.max(0,Math.min(1,Number(parsed.confidence??.6))),provider:'huggingface',model}}catch{return{...local,provider:'internal-fallback'}}}}
export const sentimentProvider:SentimentProvider=new HybridSentimentProvider();
