'use client';

import { AlertTriangle, BrainCircuit, CheckCircle2, Lightbulb, LoaderCircle, ShieldAlert, Sparkles, Target } from 'lucide-react';
import { useEffect, useState } from 'react';

export type AiResult={executive_summary:string;dominant_sentiment:string;key_topics:Array<{topic:string;evidence_count:number;explanation:string}>;risks:Array<{title:string;severity:string;explanation:string;evidence_ids:string[]}>;opportunities:Array<{title:string;explanation:string;evidence_ids:string[]}>;recommendations:Array<{action:string;reason:string;priority:string}>;limitations:string[]};
export type SavedAiReport={id:string;status:string;provider:string;model:string;input_count:number;result:AiResult;token_usage?:Record<string,number>|null;created_at:string;completed_at?:string|null};

export function AiAnalysisPanel({monitorId,mentionCount,onReport}:{monitorId:string;mentionCount:number;onReport?:(report:SavedAiReport|null)=>void}){
  const [report,setReport]=useState<SavedAiReport|null>(null),[loading,setLoading]=useState(true),[generating,setGenerating]=useState(false),[error,setError]=useState('');
  useEffect(()=>{let active=true;fetch(`/api/ai/reports?monitorId=${encodeURIComponent(monitorId)}`,{cache:'no-store'}).then(async response=>(await response.json()) as {report?:SavedAiReport|null}).then(value=>{if(active){const next=value.report??null;setReport(next);onReport?.(next)}}).catch(()=>{}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[monitorId,onReport]);
  const generate=async()=>{setGenerating(true);setError('');try{const response=await fetch('/api/ai/reports',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({monitorId})});const value=await response.json() as {report?:SavedAiReport;error?:string};if(!response.ok||!value.report)throw new Error(value.error??'Falha ao gerar análise.');setReport(value.report);onReport?.(value.report)}catch(reason){setError(reason instanceof Error?reason.message:'Falha ao gerar análise.')}finally{setGenerating(false)}};
  if(loading)return <section className="mt-4 rounded-2xl border border-slate-200 bg-white p-6"><div className="flex items-center gap-3 text-sm text-slate-500"><LoaderCircle className="animate-spin text-blue-600" size={19}/>Carregando análise de IA...</div></section>;
  return <section className="mt-4 overflow-hidden rounded-2xl border border-violet-200 bg-white"><div className="flex flex-col justify-between gap-4 bg-gradient-to-r from-slate-950 to-violet-950 p-6 text-white sm:flex-row sm:items-center"><div className="flex gap-4"><div className="grid h-11 w-11 flex-none place-items-center rounded-xl bg-white/10 text-violet-200"><BrainCircuit size={23}/></div><div><div className="text-[10px] font-semibold uppercase tracking-[.16em] text-violet-300">Inteligência artificial</div><h2 className="mt-1 text-lg font-semibold">Análise executiva do monitoramento</h2><p className="mt-1 text-xs text-slate-300">Somente evidências reais dos últimos 30 dias. O resultado fica salvo.</p></div></div><button disabled={generating||mentionCount===0} onClick={()=>void generate()} className="inline-flex h-10 flex-none items-center justify-center gap-2 rounded-xl bg-violet-500 px-4 text-sm font-semibold text-white hover:bg-violet-400 disabled:cursor-not-allowed disabled:opacity-50">{generating?<LoaderCircle className="animate-spin" size={16}/>:<Sparkles size={16}/>} {generating?'Analisando...':report?'Atualizar análise':'Gerar análise com IA'}</button></div>{error?<div role="alert" className="flex gap-3 border-b border-red-100 bg-red-50 p-4 text-sm text-red-800"><AlertTriangle className="flex-none" size={18}/>{error}</div>:null}{report?<ReportBody report={report}/>:<div className="p-8 text-center"><Sparkles className="mx-auto text-violet-300" size={31}/><h3 className="mt-3 font-semibold">Análise ainda não gerada</h3><p className="mx-auto mt-1 max-w-lg text-sm leading-6 text-slate-500">Clique no botão para cruzar as menções deste monitoramento. A IA não substitui a revisão humana e não criará métricas ausentes.</p></div>}</section>;
}

function ReportBody({report}:{report:SavedAiReport}){const result=report.result;return <div className="p-6"><div className="grid gap-4 lg:grid-cols-[1.5fr_1fr]"><div><div className="flex items-center gap-2 text-sm font-semibold"><Sparkles size={17} className="text-violet-600"/>Resumo executivo</div><p className="mt-3 text-sm leading-7 text-slate-600">{result.executive_summary}</p></div><div className="rounded-xl bg-slate-50 p-4"><div className="text-[10px] font-semibold uppercase tracking-wider text-slate-400">Sentimento predominante</div><div className="mt-2 text-lg font-semibold capitalize">{result.dominant_sentiment}</div><div className="mt-3 text-xs text-slate-500">{report.input_count} evidências · {report.model}</div><div className="mt-1 text-[10px] text-slate-400">Gerado em {new Date(report.completed_at??report.created_at).toLocaleString('pt-BR')}</div></div></div><div className="mt-6 grid gap-4 lg:grid-cols-2"><Group icon={Target} title="Assuntos principais">{result.key_topics.map(item=><Item key={item.topic} title={`${item.topic} · ${item.evidence_count}`} text={item.explanation}/>)}</Group><Group icon={ShieldAlert} title="Riscos">{result.risks.length?result.risks.map(item=><Item key={item.title} title={`${item.title} · ${item.severity}`} text={item.explanation}/>):<p className="text-sm text-slate-500">Nenhum risco sustentado pelas evidências.</p>}</Group><Group icon={Lightbulb} title="Oportunidades">{result.opportunities.length?result.opportunities.map(item=><Item key={item.title} title={item.title} text={item.explanation}/>):<p className="text-sm text-slate-500">Nenhuma oportunidade sustentada pelas evidências.</p>}</Group><Group icon={CheckCircle2} title="Recomendações">{result.recommendations.map(item=><Item key={item.action} title={`${item.action} · prioridade ${item.priority}`} text={item.reason}/>)}</Group></div>{result.limitations.length?<div className="mt-5 rounded-xl border border-amber-200 bg-amber-50 p-4"><div className="text-xs font-semibold text-amber-900">Limitações da análise</div><ul className="mt-2 list-disc space-y-1 pl-4 text-xs leading-5 text-amber-800">{result.limitations.map(item=><li key={item}>{item}</li>)}</ul></div>:null}</div>}
function Group({icon:Icon,title,children}:{icon:React.ElementType;title:string;children:React.ReactNode}){return <section className="rounded-xl border border-slate-100 p-4"><div className="flex items-center gap-2 text-sm font-semibold"><Icon size={17} className="text-violet-600"/>{title}</div><div className="mt-3 space-y-3">{children}</div></section>}
function Item({title,text}:{title:string;text:string}){return <div><div className="text-xs font-semibold capitalize text-slate-800">{title}</div><p className="mt-1 text-xs leading-5 text-slate-500">{text}</p></div>}
