'use client';
import { Activity, Bell, BellRing, BookOpenText, ChevronDown, ChevronRight, CircleGauge, Database, FileBarChart, LayoutDashboard, Menu, MessageSquareText, Newspaper, Plus, Search, Settings, Video, X } from 'lucide-react';
import { useCallback, useEffect, useState, type ElementType } from 'react';
import { MonitorWizard, WorkspaceView } from './workspace-views';

type DashboardData={connected:boolean;metrics:{today:number;week:number;month:number;sources:number;monitors:number};mentions:Array<{id:string;matched_text:string|null;relevance_score:number;created_at:string;articles:{title:string;description:string|null;url:string;published_at:string;sources:{name:string}|null}|null;monitors:{name:string}|null}>;updatedAt?:string};
const empty:DashboardData={connected:false,metrics:{today:0,week:0,month:0,sources:0,monitors:0},mentions:[]};
const nav=[['Visão geral',LayoutDashboard],['Monitoramentos',CircleGauge],['Menções',MessageSquareText],['Fontes',Newspaper],['Análises',Activity],['Alertas',BellRing],['Relatórios',FileBarChart],['YouTube',Video],['Configurações',Settings]] as const;
function Brand(){return <div className="flex h-[72px] items-center gap-3 px-5"><div className="flex h-10 w-10 items-end justify-center gap-[3px] rounded-xl bg-blue-600 pb-2.5"><i className="h-2 w-[3px] rounded-full bg-white/70"/><i className="h-4 w-[3px] rounded-full bg-white"/><i className="h-6 w-[3px] rounded-full bg-white"/><i className="h-3 w-[3px] rounded-full bg-white/80"/></div><div><div className="text-[15px] font-bold tracking-[.08em] text-white">PULSO</div><div className="mt-0.5 text-[9px] font-medium tracking-[.2em] text-slate-500">MEDIA INTELLIGENCE</div></div></div>}
export function Dashboard(){
 const [mobileOpen,setMobileOpen]=useState(false),[active,setActive]=useState('Visão geral'),[wizard,setWizard]=useState(false),[data,setData]=useState<DashboardData>(empty),[loading,setLoading]=useState(true);
 const refreshDashboard=useCallback(()=>fetch('/api/dashboard',{cache:'no-store'}).then(async r=>(await r.json()) as DashboardData).then(value=>setData(value)).catch(()=>setData(empty)).finally(()=>setLoading(false)),[]);
 useEffect(()=>{void refreshDashboard()},[refreshDashboard]);
 return <div className="min-h-screen bg-[#F3F5F7] lg:pl-[252px]">{mobileOpen?<button aria-label="Fechar menu" className="fixed inset-0 z-40 bg-slate-950/45 lg:hidden" onClick={()=>setMobileOpen(false)}/>:null}
  <aside className={`fixed inset-y-0 left-0 z-50 flex w-[252px] flex-col border-r border-white/[.06] bg-[#101318] shadow-2xl transition-transform ${mobileOpen?'translate-x-0':'-translate-x-full'} lg:translate-x-0`}><div className="flex items-center justify-between"><Brand/><button aria-label="Fechar menu" className="mr-4 rounded-lg p-2 text-slate-400 lg:hidden" onClick={()=>setMobileOpen(false)}><X size={20}/></button></div><button className="mx-4 mt-2 rounded-xl border border-white/[.08] bg-white/[.045] p-3 text-left"><div className="text-[10px] font-semibold uppercase tracking-[.12em] text-slate-500">Projeto atual</div><div className="mt-1.5 flex items-center justify-between text-sm font-medium text-slate-100">Selecione um projeto <ChevronDown size={15}/></div></button><div className="px-5 pb-2 pt-6 text-[9px] font-semibold uppercase tracking-[.18em] text-slate-600">Workspace</div><nav className="flex-1 space-y-1 px-3">{nav.map(([label,Icon])=><button key={label} onClick={()=>{setActive(label);setMobileOpen(false)}} className={`relative flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-sm transition ${active===label?'bg-blue-600 font-medium text-white':'text-slate-400 hover:bg-white/[.055] hover:text-white'}`}><Icon size={17}/>{label}{active===label?<span className="absolute -left-3 h-5 w-[3px] rounded-r-full bg-blue-300"/>:null}</button>)}</nav><div className="p-3"><div className="rounded-xl border border-white/[.07] bg-white/[.035] p-3"><div className="flex items-center justify-between text-[10px] text-slate-500"><span>BANCO DE DADOS</span><span className={data.connected?'text-emerald-400':'text-amber-400'}>{data.connected?'Conectado':'Aguardando'}</span></div><div className="mt-2 text-xs text-slate-400">{data.connected?'Dados reais sincronizados':'Configure o Supabase na Vercel'}</div></div></div></aside>
  <header className="sticky top-0 z-30 flex h-[68px] items-center border-b border-slate-200 bg-white/95 px-4 backdrop-blur-xl lg:px-8"><button aria-label="Abrir menu" className="mr-3 rounded-xl border border-slate-200 p-2 lg:hidden" onClick={()=>setMobileOpen(true)}><Menu size={20}/></button><div className="mr-6 hidden xl:block"><div className="text-[10px] font-semibold uppercase tracking-[.12em] text-slate-400">Área atual</div><div className="text-sm font-semibold">{active}</div></div><div className="relative hidden max-w-xl flex-1 md:block"><Search className="absolute left-3.5 top-3 text-slate-400" size={17}/><input className="h-10 w-full rounded-xl border border-slate-200 bg-slate-50 pl-10 text-sm outline-none focus:border-blue-400" placeholder="Pesquisar na base de mídia..."/></div><button className="ml-auto rounded-xl p-2.5 text-slate-500"><Bell size={19}/></button><div className="ml-2 grid h-8 w-8 place-items-center rounded-lg bg-slate-900 text-xs font-semibold text-white">AR</div></header>
  <main key={active} className="enter mx-auto max-w-[1540px] p-4 sm:p-6 lg:p-8">{active==='Visão geral'?<Overview data={data} loading={loading} onNew={()=>setWizard(true)}/>:<WorkspaceView view={active} data={data} onNewMonitor={()=>setWizard(true)}/>}</main>{wizard?<MonitorWizard connected={data.connected} onClose={()=>setWizard(false)} onSaved={()=>{setWizard(false);setActive('Monitoramentos');void refreshDashboard()}}/>:null}
 </div>
}
function Overview({data,loading,onNew}:{data:DashboardData;loading:boolean;onNew:()=>void}){const m=data.metrics;const cards:Array<[string,number,ElementType]>=[['Menções hoje',m.today,MessageSquareText],['Últimos 7 dias',m.week,Activity],['Últimos 30 dias',m.month,BookOpenText],['Fontes ativas',m.sources,Database],['Monitores ativos',m.monitors,CircleGauge]];return <><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><div className="mb-2 flex items-center gap-2 text-[11px] text-slate-400">Sua organização <ChevronRight size={11}/> Projeto atual</div><h1 className="text-[29px] font-semibold tracking-[-.035em]">Visão geral</h1><p className="mt-1 text-sm text-slate-500">Dados coletados das suas fontes e monitoramentos.</p></div><button onClick={onNew} className="inline-flex h-10 items-center justify-center gap-2 rounded-xl bg-blue-600 px-4 text-sm font-semibold text-white"><Plus size={17}/>Novo monitoramento</button></div>
 {!data.connected&&!loading?<div className="mt-6 flex gap-4 rounded-2xl border border-amber-200 bg-amber-50 p-5"><Database className="text-amber-600"/><div><h2 className="font-semibold text-amber-950">Aguardando conexão com o Supabase</h2><p className="mt-1 text-sm text-amber-800">Nenhum valor fictício é exibido. Após configurar as variáveis e executar a coleta, os dados reais aparecerão aqui.</p></div></div>:null}
 <section className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{cards.map(([label,value,Icon])=><div key={label} className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-start justify-between"><span className="text-xs font-medium text-slate-500">{label}</span><Icon size={17} className="text-blue-600"/></div><div className="mt-5 text-3xl font-semibold tracking-tight">{loading?'—':value.toLocaleString('pt-BR')}</div></div>)}</section>
 <section className="mt-4 rounded-2xl border border-slate-200 bg-white"><div className="border-b border-slate-100 p-5"><h2 className="font-semibold">Menções recentes</h2><p className="mt-1 text-xs text-slate-500">Somente publicações reais encontradas pelos coletores</p></div>{data.mentions.length?data.mentions.map(x=><article key={x.id} className="border-b border-slate-100 p-5 last:border-0"><div className="flex items-center gap-2 text-xs text-slate-500"><b className="text-slate-700">{x.articles?.sources?.name??'Fonte'}</b><span>•</span><span>{new Date(x.created_at).toLocaleString('pt-BR')}</span></div><h3 className="mt-2 font-semibold">{x.articles?.title}</h3><p className="mt-1 text-sm text-slate-500">{x.articles?.description}</p><a href={x.articles?.url} target="_blank" rel="noreferrer" className="mt-3 inline-block text-xs font-semibold text-blue-600">Abrir matéria →</a></article>):<div className="grid min-h-64 place-items-center p-8 text-center"><div><Newspaper className="mx-auto text-slate-300" size={32}/><h3 className="mt-3 font-semibold">Nenhuma menção coletada ainda</h3><p className="mt-1 text-sm text-slate-500">Cadastre um monitor e execute a coleta para começar.</p></div></div>}</section></>}
