'use client';
import { BellRing, Check, ChevronLeft, ChevronRight, CircleGauge, Database, FileBarChart, Globe2, KeyRound, Newspaper, Plus, Radio, Search, Settings, Video, X } from 'lucide-react';
import { useState } from 'react';

type ViewData={connected:boolean;metrics:{sources:number;monitors:number};mentions:Array<{id:string;created_at:string;relevance_score:number;articles:{title:string;description:string|null;url:string;sources:{name:string}|null}|null;monitors:{name:string}|null}>};
const panel='rounded-2xl border border-slate-200 bg-white';
const primary='inline-flex h-10 items-center justify-center gap-2 rounded-xl bg-blue-600 px-4 text-sm font-semibold text-white hover:bg-blue-700';
const secondary='inline-flex h-10 items-center justify-center gap-2 rounded-xl border border-slate-200 bg-white px-4 text-sm font-semibold text-slate-700 hover:bg-slate-50';
const input='h-10 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm outline-none focus:border-blue-500 focus:ring-3 focus:ring-blue-100';
const feeds=[
 ['Agência Brasil — Últimas Notícias','agenciabrasil.ebc.com.br','Nacional'],['Agência Brasil — Política','agenciabrasil.ebc.com.br','Política'],['Agência Brasil — Economia','agenciabrasil.ebc.com.br','Economia'],['Agência Brasil — Justiça','agenciabrasil.ebc.com.br','Governo'],['Agência Brasil — Saúde','agenciabrasil.ebc.com.br','Saúde'],['Câmara — Últimas Notícias','camara.leg.br','Governo'],['Câmara — Política','camara.leg.br','Política'],['Câmara — Economia','camara.leg.br','Economia'],['Câmara — Segurança','camara.leg.br','Segurança'],['Câmara — Eleições','camara.leg.br','Política']
];
function Head({title,description,action}:{title:string;description:string;action?:React.ReactNode}){return <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><div className="mb-2 flex items-center gap-2 text-[11px] text-slate-400">Sua organização <ChevronRight size={11}/> Projeto atual</div><h1 className="text-[29px] font-semibold tracking-[-.035em]">{title}</h1><p className="mt-1 text-sm text-slate-500">{description}</p></div>{action}</div>}
function Empty({icon:Icon,title,text,action}:{icon:React.ElementType;title:string;text:string;action?:React.ReactNode}){return <div className={`${panel} mt-6 grid min-h-80 place-items-center p-8 text-center`}><div><div className="mx-auto grid h-12 w-12 place-items-center rounded-2xl bg-slate-100 text-slate-400"><Icon size={22}/></div><h2 className="mt-4 font-semibold">{title}</h2><p className="mx-auto mt-1 max-w-md text-sm leading-6 text-slate-500">{text}</p>{action?<div className="mt-5">{action}</div>:null}</div></div>}
function Sources(){return <><Head title="Fontes RSS" description="Catálogo inicial de feeds públicos e oficiais preparado para a primeira coleta."/><div className="mt-6 flex gap-3 rounded-2xl border border-blue-200 bg-blue-50 p-4 text-sm text-blue-900"><Radio className="flex-none text-blue-600" size={20}/><p>Estes feeds são reais. O status de coleta ficará disponível somente depois que o Supabase for conectado e o coletor executado.</p></div><div className={`${panel} mt-4 overflow-hidden`}><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead className="bg-slate-50 text-[11px] uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">Fonte</th><th className="px-5 py-3">Domínio</th><th className="px-5 py-3">Categoria</th><th className="px-5 py-3">Tipo</th><th className="px-5 py-3">Situação</th></tr></thead><tbody>{feeds.map(f=><tr key={f[0]} className="border-t border-slate-100"><td className="px-5 py-4 font-semibold">{f[0]}</td><td className="px-5 py-4 text-slate-500">{f[1]}</td><td className="px-5 py-4 text-slate-600">{f[2]}</td><td className="px-5 py-4"><span className="rounded-full bg-blue-50 px-2 py-1 text-[11px] font-semibold text-blue-700">RSS</span></td><td className="px-5 py-4"><span className="rounded-full bg-amber-50 px-2 py-1 text-[11px] font-semibold text-amber-700">Aguardando banco</span></td></tr>)}</tbody></table></div></div></>}
function Mentions({data}:{data:ViewData}){return <><Head title="Central de menções" description="Publicações reais relacionadas aos seus monitoramentos."/><div className={`${panel} mt-6 p-4`}><div className="relative"><Search className="absolute left-3 top-3 text-slate-400" size={17}/><input className={`${input} pl-9`} placeholder="Pesquisar nas menções coletadas..."/></div></div>{data.mentions.length?<div className="mt-3 space-y-3">{data.mentions.map(m=><article key={m.id} className={`${panel} p-5`}><div className="text-xs text-slate-500">{m.articles?.sources?.name} · {new Date(m.created_at).toLocaleString('pt-BR')}</div><h2 className="mt-2 font-semibold">{m.articles?.title}</h2><p className="mt-1 text-sm text-slate-500">{m.articles?.description}</p><a className="mt-3 inline-block text-xs font-semibold text-blue-600" href={m.articles?.url} target="_blank" rel="noreferrer">Abrir publicação →</a></article>)}</div>:<Empty icon={Newspaper} title="Nenhuma menção real encontrada" text="Após criar um monitor e executar o coletor, as publicações correspondentes aparecerão aqui."/>}</>}
function Placeholder({view,icon:Icon}:{view:string;icon:React.ElementType}){return <><Head title={view} description="Esta área será alimentada exclusivamente com dados reais."/><Empty icon={Icon} title={`Sem dados em ${view.toLowerCase()}`} text="Não exibimos exemplos ou valores inventados. Conecte o banco e execute a coleta para preencher esta área."/></>}
export function WorkspaceView({view,data,onNewMonitor}:{view:string;data:ViewData;onNewMonitor:()=>void}){if(view==='Fontes')return <Sources/>;if(view==='Menções')return <Mentions data={data}/>;if(view==='Monitoramentos')return <><Head title="Monitoramentos" description="Pessoas, marcas e temas acompanhados pela sua organização." action={<button onClick={onNewMonitor} className={primary}><Plus size={17}/>Novo monitoramento</button>}/><Empty icon={CircleGauge} title="Nenhum monitoramento criado" text="Crie o primeiro monitoramento para definir as palavras que serão procuradas nos feeds reais." action={<button onClick={onNewMonitor} className={primary}><Plus size={16}/>Criar monitoramento</button>}/></>;const icons:Record<string,React.ElementType>={'Análises':Globe2,'Alertas':BellRing,'Relatórios':FileBarChart,'YouTube':Video,'Configurações':Settings};return <Placeholder view={view} icon={icons[view]??Database}/>}

function Modal({onClose,children}:{onClose:()=>void;children:React.ReactNode}){return <div className="fixed inset-0 z-[80] grid place-items-center bg-slate-950/50 p-4 backdrop-blur-sm"><div className="modal-card w-full max-w-2xl rounded-[20px] bg-white shadow-2xl"><div className="flex items-center justify-between border-b border-slate-100 px-6 py-5"><div><div className="text-[9px] font-semibold uppercase tracking-[.16em] text-blue-600">Pulso Intelligence</div><h2 className="mt-1 font-semibold">Novo monitoramento</h2></div><button onClick={onClose} className="rounded-xl border border-slate-200 p-2 text-slate-400"><X size={18}/></button></div><div className="p-6">{children}</div></div></div>}
export function MonitorWizard({onClose}:{onClose:()=>void}){const [step,setStep]=useState(1);return <Modal onClose={onClose}><div className="mb-7 flex gap-2">{[1,2,3,4,5].map(n=><div key={n} className={`h-1.5 flex-1 rounded-full ${n<=step?'bg-blue-600':'bg-slate-100'}`}/>)}</div>{step===1?<div><h3 className="font-semibold">Nome do monitoramento</h3><p className="mt-1 text-sm text-slate-500">Informe a pessoa, marca ou assunto que deseja acompanhar.</p><input className={`${input} mt-5`} placeholder="Digite um nome"/></div>:step<5?<div><h3 className="font-semibold">{step===2?'Palavras obrigatórias':step===3?'Termos relacionados':'Termos excluídos'}</h3><p className="mt-1 text-sm text-slate-500">Adicione um termo por linha. Nenhum exemplo será salvo automaticamente.</p><textarea className="mt-5 min-h-32 w-full rounded-xl border border-slate-200 p-3 text-sm outline-none focus:border-blue-500" placeholder="Digite os termos..."/></div>:<div className="grid place-items-center py-8 text-center"><KeyRound size={30} className="text-blue-600"/><h3 className="mt-3 font-semibold">Conecte o Supabase para salvar</h3><p className="mt-1 max-w-sm text-sm text-slate-500">O formulário está pronto, mas nenhum dado será simulado enquanto o banco não estiver disponível.</p></div>}<div className="mt-7 flex justify-between border-t border-slate-100 pt-5"><button disabled={step===1} onClick={()=>setStep(s=>s-1)} className={`${secondary} disabled:opacity-40`}><ChevronLeft size={16}/>Voltar</button>{step<5?<button onClick={()=>setStep(s=>s+1)} className={primary}>Continuar <ChevronRight size={16}/></button>:<button onClick={onClose} className={primary}><Check size={16}/>Entendi</button>}</div></Modal>}
