import { createHash } from 'node:crypto';
import { createAdminClient } from '@/lib/supabase/server';
import { sentimentProvider } from '@/services/analysis/sentimentProvider';
import { matchKeywords, type MonitorKeyword } from '@/services/matching/keywordMatcher';
import type { CollectorResult, NormalizedContent } from '@/types/content';

type Monitor = { id: string; name: string; monitor_keywords: MonitorKeyword[] }; type Source = { id: string }; type NostrEvent = { id: string; pubkey: string; created_at: number; kind: number; content: string; tags: string[][] };
const relays = () => (process.env.NOSTR_RELAYS ?? 'wss://relay.nostr.band').split(',').map((value) => value.trim()).filter((value) => value.startsWith('wss://')).slice(0, 4);
async function source(): Promise<Source> { const db = createAdminClient(); const { data: found, error } = await db.from('sources').select('id').eq('source_type', 'nostr').limit(1).maybeSingle(); if (error) throw error; if (found) return found as Source; const { data, error: insertError } = await db.from('sources').insert({ name: 'Nostr', domain: 'nostr', source_type: 'nostr', site_url: 'https://nostr.com', country: 'BR', category: 'Redes sociais', active: true, check_interval: 30 }).select('id').single(); if (insertError) throw insertError; return data as Source; }

function queryRelay(relay: string, term: string): Promise<NostrEvent[]> {
  return new Promise((resolve, reject) => {
    const subscription = `pulso-${Math.random().toString(36).slice(2)}`; const events = new Map<string, NostrEvent>(); let settled = false;
    const socket = new WebSocket(relay); const finish = (error?: Error) => { if (settled) return; settled = true; clearTimeout(timer); try { socket.close(); } catch {} if (error && !events.size) reject(error); else resolve([...events.values()]); };
    const timer = setTimeout(() => finish(), 8_000);
    socket.onopen = () => socket.send(JSON.stringify(['REQ', subscription, { kinds: [1], search: term, since: Math.floor(Date.now() / 1000) - 7 * 86400, limit: 50 }]));
    socket.onmessage = (message) => { try { const payload = JSON.parse(String(message.data)) as unknown[]; if (payload[0] === 'EVENT' && payload[1] === subscription) { const event = payload[2] as NostrEvent; if (event?.kind === 1 && event.content) events.set(event.id, event); } else if (payload[0] === 'EOSE' && payload[1] === subscription) finish(); } catch {} };
    socket.onerror = () => finish(new Error(`Relay Nostr indisponível: ${relay}`));
  });
}
const normalize = (event: NostrEvent, relay: string): NormalizedContent => { const author = `${event.pubkey.slice(0, 10)}…`; const text = event.content.trim(); const url = `https://njump.me/${event.id}`; return { source: `Nostr · ${relay.replace('wss://', '')}`, sourceType: 'nostr', externalId: event.id, title: text.length > 140 ? `${text.slice(0, 137)}...` : text, description: text, content: text, author, url, canonicalUrl: url, publishedAt: new Date(event.created_at * 1000).toISOString(), metadata: { relay, pubkey: event.pubkey, tags: event.tags } }; };

export async function collectNostrMonitors(options: { batch?: number; totalBatches?: number } = {}): Promise<CollectorResult[]> {
  const db = createAdminClient(); const { data, error } = await db.from('monitors').select('id,name,monitor_keywords(id,keyword,type)').eq('status', 'active').order('created_at'); if (error) throw error; const total = Math.max(1, Math.min(8, options.totalBatches ?? 1)); const batch = Math.max(0, Math.min(total - 1, options.batch ?? 0)); const monitors = ((data ?? []) as Monitor[]).filter((_, index) => index % total === batch); if (!monitors.length) return []; const src = await source(); const results: CollectorResult[] = [];
  for (const monitor of monitors) {
    const started = Date.now(); const result: CollectorResult = { sourceId: src.id, found: 0, inserted: 0, duplicates: 0, mentions: 0, errors: [], durationMs: 0 }; const terms = monitor.monitor_keywords.filter((item) => item.type !== 'exclude').map((item) => item.keyword.trim()).filter(Boolean).slice(0, 5); const searches = relays().flatMap((relay) => terms.map(async (term) => ({ relay, events: await queryRelay(relay, term) }))); const settled = await Promise.allSettled(searches); const unique = new Map<string, NormalizedContent>();
    for (const item of settled) { if (item.status === 'rejected') result.errors.push(item.reason instanceof Error ? item.reason.message : 'Falha no Nostr'); else for (const event of item.value.events) unique.set(event.id, normalize(event, item.value.relay)); } result.found = unique.size;
    for (const item of unique.values()) { const match = matchKeywords(item.content, monitor.monitor_keywords); if (!match.matched) continue; const hash = createHash('sha256').update(`nostr|${item.externalId}`).digest('hex'); const { data: inserted, error: articleError } = await db.from('articles').upsert({ source_id: src.id, external_id: item.externalId, title: item.title || 'Publicação Nostr', description: item.description, content: item.content, author: item.author, url: item.url, canonical_url: item.canonicalUrl, published_at: item.publishedAt, language: 'pt-BR', category: 'Nostr', hash }, { onConflict: 'canonical_url', ignoreDuplicates: true }).select('id').maybeSingle(); if (articleError) { result.errors.push(articleError.message); continue; } let articleId = inserted?.id as string | undefined; if (!articleId) { result.duplicates++; const { data: existing } = await db.from('articles').select('id').eq('canonical_url', item.canonicalUrl).maybeSingle(); articleId = existing?.id; } else result.inserted++; if (!articleId) continue; const { data: sentiments } = await db.from('sentiment_analysis').select('id').eq('article_id', articleId).limit(1); if (!sentiments?.length) { const analysis = await sentimentProvider.analyzeSentiment(item.content); await db.from('sentiment_analysis').insert({ article_id: articleId, sentiment: analysis.sentiment, score: analysis.score, confidence: analysis.confidence, provider: analysis.provider, model: analysis.model }); } const { error: mentionError } = await db.from('mentions').upsert({ monitor_id: monitor.id, article_id: articleId, keyword_id: match.keywordId, matched_text: match.matchedText, relevance_score: match.relevanceScore }, { onConflict: 'monitor_id,article_id,keyword_id', ignoreDuplicates: true }); if (mentionError) result.errors.push(mentionError.message); else result.mentions++; }
    result.durationMs = Date.now() - started; await db.from('collection_logs').insert({ source_id: src.id, collector_type: 'nostr', status: result.errors.length ? 'partial' : 'success', items_found: result.found, new_items: result.inserted, duplicates: result.duplicates, errors: result.errors, duration_ms: result.durationMs }); results.push(result);
  }
  await db.from('sources').update({ last_checked_at: new Date().toISOString() }).eq('id', src.id); return results;
}
