'use client';

import { Check, Download, ExternalLink, Filter, Newspaper, Search, Square, X } from 'lucide-react';
import { useMemo, useState } from 'react';
import { generateClippingPdf } from '@/services/reports/generateClippingPdf';

type Mention = {
  id: string;
  matched_text?: string | null;
  relevance_score: number;
  created_at: string;
  articles: { title: string; description: string | null; author?: string | null; url: string; published_at: string | null; sources: { name: string; source_type: string } | null; sentiment_analysis?: Array<{ sentiment: string; score: number }> } | null;
  monitors: { id: string; name: string; project_id: string } | null;
};

const sourceLabels: Record<string,string> = { rss:'Notícias', news:'Notícias', youtube:'YouTube', youtube_comment:'Comentário YouTube', bluesky:'Bluesky', mastodon:'Mastodon', lemmy:'Lemmy', nostr:'Nostr' };
const sentimentLabels: Record<string,string> = { positive:'Positivo', neutral:'Neutro', negative:'Negativo', unknown:'Não analisado' };

export function ContentExplorer({mentions}:{mentions:Mention[]}) {
  const [query,setQuery]=useState(''),[monitor,setMonitor]=useState('all'),[source,setSource]=useState('all'),[sentiment,setSentiment]=useState('all'),[period,setPeriod]=useState('30'),[selected,setSelected]=useState<Set<string>>(new Set()),[openedAt]=useState(()=>Date.now());
  const monitors=useMemo(()=>[...new Map(mentions.filter(item=>item.monitors).map(item=>[item.monitors!.id,item.monitors!])).values()],[mentions]);
  const sources=useMemo(()=>[...new Set(mentions.map(item=>item.articles?.sources?.source_type).filter((value):value is string=>Boolean(value)))].sort(),[mentions]);
  const filtered=useMemo(()=>{const needle=query.trim().toLocaleLowerCase('pt-BR'),cutoff=period==='all'?0:openedAt-Number(period)*86400000;return mentions.filter(item=>{const value=item.articles?.sentiment_analysis?.[0]?.sentiment??'unknown';const text=`${item.articles?.title??''} ${item.articles?.description??''} ${item.articles?.author??''} ${item.matched_text??''}`.toLocaleLowerCase('pt-BR');return (!needle||text.includes(needle))&&(monitor==='all'||item.monitors?.id===monitor)&&(source==='all'||item.articles?.sources?.source_type===source)&&(sentiment==='all'||value===sentiment)&&(!cutoff||new Date(item.articles?.published_at??item.created_at).getTime()>=cutoff)});},[mentions,query,monitor,source,sentiment,period,openedAt]);
  const toggle=(id:string)=>setSelected(current=>{const next=new Set(current);if(next.has(id))next.delete(id);else next.add(id);return next});
  const selectedMentions=mentions.filter(item=>selected.has(item.id));
  const clear=()=>{setQuery('');setMonitor('all');setSource('all');setSentiment('all');setPeriod('30')};
  return <>
    <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><div className="mb-2 text-[11px] text-slate-400">Sua organização · Projeto atual</div><h1 className="text-[29px] font-semibold tracking-[-.035em]">Explorador de conteúdo</h1><p className="mt-1 text-sm text-slate-500">Pesquise, filtre e selecione publicações reais para o clipping.</p></div>{selected.size?<button onClick={()=>generateClippingPdf(selectedMentions)} className="inline-flex h-10 items-center justify-center gap-2 rounded-xl bg-blue-600 px-4 text-sm font-semibold text-white hover:bg-blue-700"><Download size={16}/>Baixar clipping ({selected.size})</button>:null}</div>
    <section className="mt-6 rounded-2xl border border-slate-200 bg-white p-4"><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-wider text-slate-400"><Filter size={15}/>Filtros</div><div className="mt-3 grid gap-3 lg:grid-cols-[2fr_1fr_1fr_1fr_1fr_auto]"><label className="relative"><span className="sr-only">Pesquisar</span><Search className="absolute left-3 top-3 text-slate-400" size={17}/><input value={query} onChange={event=>setQuery(event.target.value)} className="h-10 w-full rounded-xl border border-slate-200 pl-9 pr-3 text-sm outline-none focus:border-blue-500" placeholder="Título, conteúdo ou autor..."/></label><select aria-label="Monitoramento" value={monitor} onChange={event=>setMonitor(event.target.value)} className="h-10 rounded-xl border border-slate-200 px-3 text-sm"><option value="all">Todos os monitores</option>{monitors.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select><select aria-label="Fonte" value={source} onChange={event=>setSource(event.target.value)} className="h-10 rounded-xl border border-slate-200 px-3 text-sm"><option value="all">Todas as fontes</option>{sources.map(value=><option key={value} value={value}>{sourceLabels[value]??value}</option>)}</select><select aria-label="Sentimento" value={sentiment} onChange={event=>setSentiment(event.target.value)} className="h-10 rounded-xl border border-slate-200 px-3 text-sm"><option value="all">Todo sentimento</option><option value="positive">Positivo</option><option value="neutral">Neutro</option><option value="negative">Negativo</option><option value="unknown">Não analisado</option></select><select aria-label="Período" value={period} onChange={event=>setPeriod(event.target.value)} className="h-10 rounded-xl border border-slate-200 px-3 text-sm"><option value="1">Hoje</option><option value="7">7 dias</option><option value="30">30 dias</option><option value="90">90 dias</option><option value="all">Todo período</option></select><button onClick={clear} title="Limpar filtros" className="grid h-10 w-10 place-items-center rounded-xl border border-slate-200 text-slate-500 hover:bg-slate-50"><X size={17}/></button></div></section>
    <div className="mt-4 flex items-center justify-between text-sm"><span className="text-slate-500"><b className="text-slate-900">{filtered.length}</b> publicações encontradas</span>{selected.size?<button onClick={()=>setSelected(new Set())} className="text-xs font-semibold text-blue-600">Limpar seleção</button>:null}</div>
    {filtered.length?<div className="mt-3 grid gap-4 xl:grid-cols-2">{filtered.map(item=>{const article=item.articles,type=article?.sources?.source_type??'news',feeling=article?.sentiment_analysis?.[0]?.sentiment??'unknown',checked=selected.has(item.id);return <article key={item.id} className={`rounded-2xl border bg-white p-5 transition ${checked?'border-blue-400 ring-2 ring-blue-100':'border-slate-200'}`}><div className="flex items-start gap-3"><button aria-label={checked?'Remover do clipping':'Adicionar ao clipping'} onClick={()=>toggle(item.id)} className={`mt-0.5 grid h-7 w-7 flex-none place-items-center rounded-lg border ${checked?'border-blue-600 bg-blue-600 text-white':'border-slate-200 text-slate-400'}`}>{checked?<Check size={15}/>:<Square size={14}/>}</button><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2 text-[11px]"><span className="rounded-full bg-blue-50 px-2 py-1 font-semibold text-blue-700">{sourceLabels[type]??type}</span><span className="font-semibold text-slate-600">{article?.sources?.name??'Fonte'}</span><span className={`rounded-full px-2 py-1 font-medium ${feeling==='negative'?'bg-red-50 text-red-700':feeling==='positive'?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-600'}`}>{sentimentLabels[feeling]??feeling}</span></div><h2 className="mt-3 text-base font-semibold leading-6">{article?.title||'Publicação sem título'}</h2><p className="mt-2 line-clamp-3 text-sm leading-6 text-slate-500">{article?.description||item.matched_text||'Sem descrição fornecida pela fonte.'}</p><div className="mt-4 flex flex-wrap items-center justify-between gap-3 border-t border-slate-100 pt-3 text-xs text-slate-400"><span>{item.monitors?.name??'Monitor'} · {new Date(article?.published_at??item.created_at).toLocaleString('pt-BR')}{article?.author?` · ${article.author}`:''}</span>{article?.url?<a href={article.url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 font-semibold text-blue-600">Abrir original <ExternalLink size={13}/></a>:null}</div></div></div></article>})}</div>:<div className="mt-4 grid min-h-72 place-items-center rounded-2xl border border-slate-200 bg-white p-8 text-center"><div><Newspaper className="mx-auto text-slate-300" size={34}/><h2 className="mt-3 font-semibold">Nenhuma publicação encontrada</h2><p className="mt-1 text-sm text-slate-500">Altere os filtros ou aguarde uma nova coleta.</p></div></div>}
  </>;
}
