import { createAdminClient } from '@/lib/supabase/server';

export const runtime='nodejs';
export const dynamic='force-dynamic';

type ArticleRow={id:string;title:string;description:string|null;url:string;published_at:string|null;sources:{name:string}|null};
type PollEvidence={id:string;title:string;url:string;publishedAt:string|null;source:string;institute:string;state:string;stateName:string;leftPercentage:number;rightPercentage:number};
const pollTerms=/\b(datafolha|quaest|paran[aá] pesquisas|atlasintel|verit[aá]|ideia|futura|ipespe|ipec|real time big data|intenc[aã]o de voto|pesquisa eleitoral|cen[aá]rio estimulado|cen[aá]rio espont[aâ]neo|1[ºo°]? turno|2[ºo°]? turno)\b/i;
const institutes=['Datafolha','Quaest','Paraná Pesquisas','AtlasIntel','Veritá','Ipec','Ipespe','Real Time Big Data','Futura','Ideia'];
const normalize=(value:string)=>value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const candidateName=(value:string)=>value.split(/[—–|-]/)[0].trim();
function aliasesFor(candidate:string){const words=normalize(candidate).split(/\s+/).filter(word=>word.length>=3&&!['geral','eleicoes','presidente','governador','senador'].includes(word));return [...new Set([normalize(candidate),words[0],words.at(-1)].filter((item):item is string=>Boolean(item&&item.length>=3)))]}
function percentageNear(text:string,candidate:string){const normalized=normalize(text),aliases=aliasesFor(candidate),positions=aliases.flatMap(alias=>{const found:number[]=[];let cursor=normalized.indexOf(alias);while(cursor>=0){found.push(cursor);cursor=normalized.indexOf(alias,cursor+alias.length)}return found});if(!positions.length)return null;const values=[...normalized.matchAll(/(\d{1,2}(?:[.,]\d+)?)\s*%/g)].map(match=>({value:Number(match[1].replace(',','.')),index:match.index??0})).filter(item=>item.value>=0&&item.value<=100);const ranked=values.flatMap(item=>positions.map(position=>{const after=item.index>=position;const distance=after?item.index-position:position-item.index;return{...item,distance,score:distance+(after?0:18)}})).filter(item=>item.distance<=65).sort((a,b)=>a.score-b.score);return ranked[0]?.value??null}
function instituteFrom(text:string){return institutes.find(name=>normalize(text).includes(normalize(name)))??'Instituto não identificado'}
const states=[['AC','Acre'],['AL','Alagoas'],['AP','Amapá'],['AM','Amazonas'],['BA','Bahia'],['CE','Ceará'],['DF','Distrito Federal'],['ES','Espírito Santo'],['GO','Goiás'],['MA','Maranhão'],['MT','Mato Grosso'],['MS','Mato Grosso do Sul'],['MG','Minas Gerais'],['PA','Pará'],['PB','Paraíba'],['PR','Paraná'],['PE','Pernambuco'],['PI','Piauí'],['RJ','Rio de Janeiro'],['RN','Rio Grande do Norte'],['RS','Rio Grande do Sul'],['RO','Rondônia'],['RR','Roraima'],['SC','Santa Catarina'],['SP','São Paulo'],['SE','Sergipe'],['TO','Tocantins']] as const;
function stateFrom(title:string){const normalized=normalize(title);for(const [code,name] of states){const fullName=normalize(name).replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),prefix='(?:em|no|na|de|do|da)';const byName=new RegExp(`\\b${prefix}\\s+(?:estado\\s+(?:de|do|da)\\s+)?${fullName}\\b`),byCode=new RegExp(`\\b${prefix}\\s+${code.toLowerCase()}\\b`);if(byName.test(normalized)||byCode.test(normalized))return{code,name}}if(/\b(nacional|no brasil|do brasil)\b/.test(normalized))return{code:'BR',name:'Nacional'};return null}

export async function GET(request:Request){
 try{const url=new URL(request.url),leftId=url.searchParams.get('left'),rightId=url.searchParams.get('right');if(!leftId||!rightId||leftId===rightId)return Response.json({error:'Selecione dois monitoramentos diferentes.'},{status:400});const db=createAdminClient();const {data:monitors,error:monitorError}=await db.from('monitors').select('id,name').in('id',[leftId,rightId]);if(monitorError)throw monitorError;const left=monitors?.find(item=>item.id===leftId),right=monitors?.find(item=>item.id===rightId);if(!left||!right)return Response.json({error:'Monitoramento não encontrado.'},{status:404});const articleIds:string[]=[];for(let from=0;from<5000;from+=1000){const {data,error}=await db.from('mentions').select('article_id').in('monitor_id',[leftId,rightId]).order('created_at',{ascending:false}).range(from,from+999);if(error)throw error;const page=(data??[]) as Array<{article_id:string}>;articleIds.push(...page.map(item=>item.article_id));if(page.length<1000)break}const uniqueIds=[...new Set(articleIds)],articles:ArticleRow[]=[];for(let from=0;from<uniqueIds.length;from+=200){const {data,error}=await db.from('articles').select('id,title,description,url,published_at,sources(name)').in('id',uniqueIds.slice(from,from+200));if(error)throw error;articles.push(...((data??[]) as unknown as ArticleRow[]))}const leftName=candidateName(left.name),rightName=candidateName(right.name);const candidates=articles.flatMap(article=>{const title=article.title,state=stateFrom(title);if(!title.includes('%')||!pollTerms.test(title)||!state)return[];const leftPercentage=percentageNear(title,leftName),rightPercentage=percentageNear(title,rightName);if(leftPercentage===null||rightPercentage===null)return[];return[{id:article.id,title:article.title,url:article.url,publishedAt:article.published_at,source:article.sources?.name??'Fonte não identificada',institute:instituteFrom(title),state:state.code,stateName:state.name,leftPercentage,rightPercentage} satisfies PollEvidence]}).sort((a,b)=>new Date(b.publishedAt??0).getTime()-new Date(a.publishedAt??0).getTime());const byState=new Map<string,PollEvidence>();for(const item of candidates)if(!byState.has(item.state))byState.set(item.state,item);const evidence=[...byState.values()].sort((a,b)=>a.state==='BR'?-1:b.state==='BR'?1:a.state.localeCompare(b.state,'pt-BR'));const average=evidence.length?{leftPercentage:evidence.reduce((sum,item)=>sum+item.leftPercentage,0)/evidence.length,rightPercentage:evidence.reduce((sum,item)=>sum+item.rightPercentage,0)/evidence.length,stateCount:evidence.length}:null;return Response.json({left:{id:left.id,name:leftName},right:{id:right.id,name:rightName},evidence,average});
 }catch(error){console.error('[api/election-polls]',error);const detail=error instanceof Error?error.message:typeof error==='object'&&error&&'message' in error?String(error.message):'';return Response.json({error:detail.includes('Supabase não configurado')?'A chave SUPABASE_SERVICE_ROLE_KEY não está configurada na Vercel.':'Não foi possível analisar as pesquisas eleitorais.'},{status:500})}
}
