import { createReadClient } from '@/lib/supabase/server';

export const runtime='nodejs';
export const dynamic='force-dynamic';

type MentionRow={article_id:string;articles:{id:string;title:string;description:string|null;url:string;published_at:string|null;sources:{name:string}|null}|null};
const pollTerms=/\b(datafolha|quaest|paran[aá] pesquisas|atlasintel|ideia|futura|ipespe|ipec|real time big data|intenc[aã]o de voto|pesquisa eleitoral|cen[aá]rio estimulado|cen[aá]rio espont[aâ]neo|1[ºo°]? turno|2[ºo°]? turno)\b/i;
const institutes=['Datafolha','Quaest','Paraná Pesquisas','AtlasIntel','Ipec','Ipespe','Real Time Big Data','Futura','Ideia'];
const normalize=(value:string)=>value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const candidateName=(value:string)=>value.split(/[—–|-]/)[0].trim();
function percentageNear(text:string,candidate:string){const normalized=normalize(text),needle=normalize(candidate),positions:number[]=[];let cursor=normalized.indexOf(needle);while(cursor>=0){positions.push(cursor);cursor=normalized.indexOf(needle,cursor+needle.length)}if(!positions.length)return null;const values=[...normalized.matchAll(/(\d{1,2}(?:[.,]\d+)?)\s*%/g)].map(match=>({value:Number(match[1].replace(',','.')),index:match.index??0})).filter(item=>item.value>=0&&item.value<=100);const closest=values.map(item=>({...item,distance:Math.min(...positions.map(position=>Math.abs(item.index-position)))})).filter(item=>item.distance<=100).sort((a,b)=>a.distance-b.distance)[0];return closest?.value??null}
function instituteFrom(text:string){return institutes.find(name=>normalize(text).includes(normalize(name)))??'Instituto não identificado'}

export async function GET(request:Request){
 try{const url=new URL(request.url),leftId=url.searchParams.get('left'),rightId=url.searchParams.get('right');if(!leftId||!rightId||leftId===rightId)return Response.json({error:'Selecione dois monitoramentos diferentes.'},{status:400});const db=createReadClient();const {data:monitors,error:monitorError}=await db.from('monitors').select('id,name').in('id',[leftId,rightId]);if(monitorError)throw monitorError;const left=monitors?.find(item=>item.id===leftId),right=monitors?.find(item=>item.id===rightId);if(!left||!right)return Response.json({error:'Monitoramento não encontrado.'},{status:404});const rows:MentionRow[]=[];for(let from=0;from<5000;from+=1000){const {data,error}=await db.from('mentions').select('article_id,articles(id,title,description,url,published_at,sources(name))').in('monitor_id',[leftId,rightId]).order('created_at',{ascending:false}).range(from,from+999);if(error)throw error;const page=(data??[]) as unknown as MentionRow[];rows.push(...page);if(page.length<1000)break}const unique=new Map<string,MentionRow['articles']>();rows.forEach(row=>{if(row.articles)unique.set(row.articles.id,row.articles)});const leftName=candidateName(left.name),rightName=candidateName(right.name);const evidence=[...unique.values()].flatMap(article=>{if(!article)return[];const text=`${article.title} ${article.description??''}`;if(!pollTerms.test(text))return[];const leftPercentage=percentageNear(text,leftName),rightPercentage=percentageNear(text,rightName);if(leftPercentage===null&&rightPercentage===null)return[];return[{id:article.id,title:article.title,url:article.url,publishedAt:article.published_at,source:article.sources?.name??'Fonte não identificada',institute:instituteFrom(text),leftPercentage,rightPercentage}]}).sort((a,b)=>new Date(b.publishedAt??0).getTime()-new Date(a.publishedAt??0).getTime());return Response.json({left:{id:left.id,name:leftName},right:{id:right.id,name:rightName},evidence});
 }catch(error){console.error('[api/election-polls]',error);return Response.json({error:'Não foi possível analisar as pesquisas eleitorais.'},{status:500})}
}
