type ReportMention = { created_at:string; relevance_score:number; matched_text:string|null; articles:{title:string;description:string|null;url:string;published_at:string|null;sources:{name:string}|null;sentiment_analysis:Array<{sentiment:string;score:number}>}|null };
type AiPdfResult={executive_summary:string;dominant_sentiment:string;key_topics:Array<{topic:string;evidence_count:number;explanation:string}>;risks:Array<{title:string;severity:string;explanation:string}>;opportunities:Array<{title:string;explanation:string}>;recommendations:Array<{action:string;reason:string;priority:string}>;limitations:string[]};
export type MonitorPdfData = { name:string;createdAt:string;keywords:Array<{keyword:string;type:string}>;metrics:{today:number;week:number;month:number;total:number;averageRelevance:number};daily:Array<{date:string;count:number}>;sentiment:{positive:number;neutral:number;negative:number;unknown:number};topSources:Array<{name:string;count:number}>;recent:ReportMention[];aiReport?:AiPdfResult|null };
const clean=(value:string)=>value.replace(/[\u0000-\u001f]/g,' ').replace(/\s+/g,' ').trim();
const safeName=(value:string)=>value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9]+/g,'-').replace(/^-|-$/g,'').toLowerCase();

export async function generateMonitorPdf(monitor:MonitorPdfData){
 const {jsPDF}=await import('jspdf'); const doc=new jsPDF({unit:'mm',format:'a4',compress:true}); const width=doc.internal.pageSize.getWidth(),height=doc.internal.pageSize.getHeight(),margin=16;let y=0;
 const pageIfNeeded=(needed:number)=>{if(y+needed<=height-18)return;doc.addPage();y=18};
 const heading=(title:string)=>{pageIfNeeded(15);doc.setFont('helvetica','bold');doc.setFontSize(13);doc.setTextColor(15,23,42);doc.text(title,margin,y);y+=8};
 const paragraph=(text:string,maxWidth=width-margin*2)=>{doc.setFont('helvetica','normal');doc.setFontSize(9);doc.setTextColor(71,85,105);const lines=doc.splitTextToSize(clean(text),maxWidth) as string[];pageIfNeeded(lines.length*4+3);doc.text(lines,margin,y);y+=lines.length*4+3};
 doc.setFillColor(15,23,42);doc.rect(0,0,width,48,'F');doc.setFillColor(37,99,235);doc.roundedRect(margin,11,12,12,3,3,'F');doc.setFont('helvetica','bold');doc.setFontSize(10);doc.setTextColor(255,255,255);doc.text('P',margin+6,19,{align:'center'});doc.setFontSize(9);doc.text('PULSO MEDIA INTELLIGENCE',margin+17,16);doc.setFontSize(19);doc.text(clean(monitor.name),margin,36);doc.setFont('helvetica','normal');doc.setFontSize(8);doc.setTextColor(203,213,225);doc.text(`Relatório gerado em ${new Date().toLocaleString('pt-BR')}`,width-margin,17,{align:'right'});y=59;
 const cards:Array<[string,string]>=[['Hoje',String(monitor.metrics.today)],['7 dias',String(monitor.metrics.week)],['30 dias',String(monitor.metrics.month)],['Total',String(monitor.metrics.total)],['Relevância',`${Math.round(monitor.metrics.averageRelevance*100)}%`]],gap=3,cardWidth=(width-margin*2-gap*4)/5;
 cards.forEach(([label,value],index)=>{const x=margin+index*(cardWidth+gap);doc.setFillColor(248,250,252);doc.setDrawColor(226,232,240);doc.roundedRect(x,y,cardWidth,22,2,2,'FD');doc.setFont('helvetica','normal');doc.setFontSize(7);doc.setTextColor(100,116,139);doc.text(label,x+3,y+7);doc.setFont('helvetica','bold');doc.setFontSize(13);doc.setTextColor(15,23,42);doc.text(value,x+3,y+16)});y+=32;
 heading('Leitura executiva');const totalSentiment=monitor.sentiment.positive+monitor.sentiment.neutral+monitor.sentiment.negative+monitor.sentiment.unknown;const sentimentRanking:Array<[string,number]>=[['positivo',monitor.sentiment.positive],['neutro',monitor.sentiment.neutral],['negativo',monitor.sentiment.negative]];const dominant=sentimentRanking.sort((a,b)=>b[1]-a[1])[0];const peak=[...monitor.daily].sort((a,b)=>b.count-a.count)[0];paragraph(monitor.metrics.total?`O monitoramento acumulou ${monitor.metrics.total} menções, com relevância média de ${Math.round(monitor.metrics.averageRelevance*100)}%. O sentimento predominante foi ${dominant[0]} (${dominant[1]} menções analisadas). ${peak?`O maior volume recente ocorreu em ${new Date(`${peak.date}T12:00:00`).toLocaleDateString('pt-BR')}, com ${peak.count} menções.`:''}`:'Ainda não há menções suficientes para produzir uma leitura executiva. O documento registra o estado atual do monitoramento.');
 heading('Evolução nos últimos 7 dias');const chartHeight=31,chartWidth=width-margin*2,barGap=3,barWidth=(chartWidth-barGap*6)/7,maximum=Math.max(1,...monitor.daily.map(item=>item.count));monitor.daily.forEach((item,index)=>{const barHeight=Math.max(1,(item.count/maximum)*23),x=margin+index*(barWidth+barGap);doc.setFillColor(37,99,235);doc.roundedRect(x,y+chartHeight-barHeight,barWidth,barHeight,1,1,'F');doc.setFontSize(7);doc.setTextColor(71,85,105);doc.text(String(item.count),x+barWidth/2,y+chartHeight-barHeight-2,{align:'center'});doc.text(new Date(`${item.date}T12:00:00`).toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit'}),x+barWidth/2,y+chartHeight+5,{align:'center'})});y+=chartHeight+13;
 heading('Sentimento');const sentiments:Array<[string,number,[number,number,number]]>=[['Positivo',monitor.sentiment.positive,[16,185,129]],['Neutro',monitor.sentiment.neutral,[100,116,139]],['Negativo',monitor.sentiment.negative,[239,68,68]],['Não analisado',monitor.sentiment.unknown,[245,158,11]]];sentiments.forEach(([label,value,color])=>{doc.setFontSize(8);doc.setTextColor(71,85,105);doc.text(label,margin,y);doc.text(String(value),width-margin,y,{align:'right'});doc.setFillColor(241,245,249);doc.roundedRect(margin+31,y-3,width-margin*2-42,3,1,1,'F');doc.setFillColor(...color);const ratio=totalSentiment?value/totalSentiment:0;if(ratio>0)doc.roundedRect(margin+31,y-3,(width-margin*2-42)*ratio,3,1,1,'F');y+=8});y+=3;
 heading('Fontes com maior presença');if(monitor.topSources.length){monitor.topSources.forEach((source,index)=>{pageIfNeeded(8);doc.setFillColor(index%2?255:248,index%2?255:250,index%2?255:252);doc.rect(margin,y-5,width-margin*2,8,'F');doc.setFont('helvetica','normal');doc.setFontSize(9);doc.setTextColor(51,65,85);doc.text(`${index+1}. ${clean(source.name)}`,margin+2,y);doc.setFont('helvetica','bold');doc.text(`${source.count} menções`,width-margin-2,y,{align:'right'});y+=8})}else paragraph('Nenhuma fonte encontrada no período.');
 heading('Termos monitorados');paragraph(monitor.keywords.map(item=>`${item.keyword} (${item.type==='exclude'?'excluído':item.type==='related'?'relacionado':'obrigatório'})`).join(' • ')||'Nenhum termo cadastrado.');
 if(monitor.aiReport){heading('Análise executiva por inteligência artificial');paragraph(monitor.aiReport.executive_summary);paragraph(`Sentimento predominante: ${monitor.aiReport.dominant_sentiment}.`);heading('Assuntos principais');monitor.aiReport.key_topics.forEach(item=>paragraph(`${item.topic} (${item.evidence_count} evidências): ${item.explanation}`));heading('Riscos identificados');if(monitor.aiReport.risks.length)monitor.aiReport.risks.forEach(item=>paragraph(`${item.title} [${item.severity}]: ${item.explanation}`));else paragraph('Nenhum risco sustentado pelas evidências.');heading('Oportunidades');if(monitor.aiReport.opportunities.length)monitor.aiReport.opportunities.forEach(item=>paragraph(`${item.title}: ${item.explanation}`));else paragraph('Nenhuma oportunidade sustentada pelas evidências.');heading('Recomendações');monitor.aiReport.recommendations.forEach(item=>paragraph(`${item.action} [prioridade ${item.priority}]: ${item.reason}`));if(monitor.aiReport.limitations.length){heading('Limitações da análise');monitor.aiReport.limitations.forEach(item=>paragraph(`• ${item}`))}}
 heading('Menções estratégicas');if(!monitor.recent.length)paragraph('Nenhuma menção coletada até a geração deste relatório.');monitor.recent.forEach((mention,index)=>{const article=mention.articles;if(!article)return;const titleLines=doc.splitTextToSize(clean(article.title),width-margin*2-6) as string[],descriptionLines=doc.splitTextToSize(clean(article.description??'').slice(0,330),width-margin*2-6) as string[];pageIfNeeded(20+titleLines.length*4+Math.min(descriptionLines.length,4)*4);doc.setFont('helvetica','bold');doc.setFontSize(10);doc.setTextColor(15,23,42);doc.text(`${index+1}.`,margin,y);doc.text(titleLines,margin+6,y);y+=titleLines.length*4+2;doc.setFont('helvetica','normal');doc.setFontSize(8);doc.setTextColor(100,116,139);const source=clean(article.sources?.name??'Fonte não identificada'),date=new Date(article.published_at??mention.created_at).toLocaleString('pt-BR');doc.text(`${source} | ${date} | ${Math.round(Number(mention.relevance_score)*100)}% de relevância`,margin+6,y);y+=5;if(descriptionLines.length){doc.setTextColor(71,85,105);doc.text(descriptionLines.slice(0,4),margin+6,y);y+=Math.min(descriptionLines.length,4)*4+1}doc.setTextColor(37,99,235);doc.textWithLink('Abrir publicação original',margin+6,y,{url:article.url});y+=10});
 const pages=doc.getNumberOfPages();for(let page=1;page<=pages;page++){doc.setPage(page);doc.setDrawColor(226,232,240);doc.line(margin,height-12,width-margin,height-12);doc.setFont('helvetica','normal');doc.setFontSize(8);doc.setTextColor(100,116,139);doc.text('Pulso Media Intelligence - dados reais coletados',margin,height-7);doc.text(`Página ${page} de ${pages}`,width-margin,height-7,{align:'right'})}
 doc.save(`pulso-${safeName(monitor.name)||'monitoramento'}-${new Date().toISOString().slice(0,10)}.pdf`);
}
